# Generated by Django 5.2 on 2025-05-06 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Delivery Plan',
                'verbose_name_plural': 'Delivery Plans',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('estimated_arrival_time', models.TimeField(blank=True, null=True, verbose_name='Estimated Arrival Time')),
                ('actual_arrival_time', models.TimeField(blank=True, null=True, verbose_name='Actual Arrival Time')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ARRIVED', 'Arrived'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Delivery Stop',
                'verbose_name_plural': 'Delivery Stops',
                'ordering': ['position'],
            },
        ),
    ]
