# Generated by Django 5.2 on 2025-05-06 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('orders', '0003_initial'),
        ('shops', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryplan',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_plans', to=settings.AUTH_USER_MODEL, verbose_name='Driver'),
        ),
        migrations.AddField(
            model_name='deliveryplan',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_plans', to='suppliers.supplier', verbose_name='Supplier'),
        ),
        migrations.AddField(
            model_name='deliverystop',
            name='delivery_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='delivery.deliveryplan', verbose_name='Delivery Plan'),
        ),
        migrations.AddField(
            model_name='deliverystop',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='deliverystop',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.shop', verbose_name='Shop'),
        ),
        migrations.AlterUniqueTogether(
            name='deliveryplan',
            unique_together={('supplier', 'date', 'driver')},
        ),
    ]
