# Generated by Django 5.2 on 2025-05-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryplan',
            name='optimize_route',
            field=models.BooleanField(default=True, verbose_name='Optimize Route'),
        ),
        migrations.AddField(
            model_name='deliveryplan',
            name='total_distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Distance (km)'),
        ),
        migrations.AddField(
            model_name='deliveryplan',
            name='total_duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Duration (min)'),
        ),
        migrations.AddField(
            model_name='deliveryplan',
            name='warehouse_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Warehouse Latitude'),
        ),
        migrations.AddField(
            model_name='deliveryplan',
            name='warehouse_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Warehouse Longitude'),
        ),
        migrations.AddField(
            model_name='deliverystop',
            name='distance_from_previous',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Distance from Previous Stop (km)'),
        ),
        migrations.AddField(
            model_name='deliverystop',
            name='duration_from_previous',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Duration from Previous Stop (min)'),
        ),
        migrations.AddField(
            model_name='deliverystop',
            name='priority',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='deliverystop',
            name='time_window_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Time Window End'),
        ),
        migrations.AddField(
            model_name='deliverystop',
            name='time_window_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Time Window Start'),
        ),
    ]
