# Generated by Django 5.2 on 2025-05-06 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliveryplan_optimize_route_and_more'),
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverystop',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.order', verbose_name='Order'),
        ),
    ]
