# Generated by Django 5.2 on 2025-05-06 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='suppliers.supplier', verbose_name='Supplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='suppliers.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'supplier')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('sku', 'supplier')},
        ),
    ]
